### PR TITLE
Fixed bugs for low zooms with tiles exceeding the world's size

### PR DESCRIPTION
**Pull request by nyurik**
For smaller zooms, or when asking for images at the edge of the world, fixed bugs with tile list generation

### CODE REVIEW

**Comment by nyurik** [comment]
CC: @flippmoke

**Comment by nyurik** [comment]
@flippmoke @camilleanne @yhahn  Hi, any updates on this PR?

**Comment by camilleanne** [comment]
hi @nyurik -- I'll review this today. Could you restart the travis build that failed? https://travis-ci.org/mapbox/abaculus/jobs/121131105

**Comment by nyurik** [comment]
@camilleanne the mapnik-config keeps failing for node 12, but seems to be fine for node 10. Hae you seen this before?  Is that a bug in the PR or somewhere else?

**Comment by nyurik** [comment]
@camilleanne If you have any questions, ping me on IRC - yurik (i'm in the # mapbox and various wikimedia-* channels)

**Comment by nyurik** [comment]
@flippmoke @camilleanne @yhahn I re-based my changes on top of your rewrite with the tile sizes. Lets merge this soonish so that it doesn't diverge too far again. There is a number of critical bug fixes that we really need in our env. Thanks!

**Pull request merged**
