### PR TITLE
io.js compatibility

### PR DESCRIPTION
**Pull request by mojodna**
This updates Travis' build targets to include node-0.12 and iojs-stable and upgrades Mapnik to 3.3.0.

Replaces #14

### CODE REVIEW

**Comment by mojodna** [comment]
Bump.

**Comment by springmeyer** [comment]
@mojodna can you stick with `~3.3.0` for mapnik? This is to avoid allowing `3.4.0` unintentionally. Other than that looks good to merge.

**Comment by mojodna** [comment]
Done.

**Comment by springmeyer** [comment]
thanks!

**Comment by mojodna** [comment]
Sweet, thanks!  I would love it if there were a new version pushed to npm as well.

**Pull request merged**
